### PR TITLE
384: Make nocache optional

### PR DESCRIPTION
**Pull request by jcarizza**
---
name: Make nocache optional
about: Ignore nocache based in a settings flag to not corrupt the S3 querysting signed URL
assignees: fabiocaccamo

---

**Describe your changes**
- Added a setting flag
- Change templates to not include md5 hash

**Related issue**
https://github.com/fabiocaccamo/django-admin-interface/issues/384

**Checklist before requesting a review**
- [x] I have performed a self-review of my code.
- [x] I have added tests for the proposed changes.
- [x] I have run the tests and there are not errors.

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
@jcarizza instead of adding a new setting, I would add a new template tag `admin_interface_static` which wraps the `static` template tag and that automatically adds the `nocache` parameter only if the url starts with `MEDIA_URL` settings (simple yet effective and zero configuration needed).

I'm sorry that you worked in another direction, I would suggest you to open an issue for discussing the solution the next time, anyway, thank you very much for this PR!

**Review by fabiocaccamo — CHANGES_REQUESTED** [review]
@jcarizza instead of adding a new setting, I would add a new template tag `admin_interface_static` which wraps the `static` template tag and that automatically adds the `nocache` parameter only if the url starts with `STATIC_URL` settings (simple yet effective and zero configuration needed).

I'm sorry that you worked in another direction, I would suggest you to discuss the solution in the issue before working on a PR the next time, anyway... thank you very much for this PR!

**Comment by jcarizza** [comment]
Hi @fabiocaccamo 

Sorry I sent the PR before a previous discussion, I needed to fix that ASAP in my application.

I think this solution would be less intrusive and simpliest.

The new template tag will check if the files are the default django storage or if they start with `STATIC_URL` and add or remove the `nocache` tag.

**Comment by fabiocaccamo** [comment]
@jcarizza any update?

**Pull request closed without merging**
