### PR TITLE
Hi again Mr Fabio, add suport a django-admin-index 

### PR DESCRIPTION
**Pull request by carlosmonari**
Hi Mr Fabio,

I saw in some comments in the package history that there is an intention to support a menu assembly option.

I created a fork with this implementation and would be very grateful if you kept this implementation in the master of your project.

I used the django-admin-index package
(https://github.com/maykinmedia/django-admin-index)
and the result was good.

I hope it is useful to anyone who wants to use it.

sample

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
@carlosmonari thank you very much, this is a very nice integration!

**Comment by fabiocaccamo** [comment]
@carlosmonari there is some problem with sticky headers when `django-admin-index` is not installed, could you fix it?

**Comment by merwok** [comment]
I find it hard to understand what this PR does

**Comment by merwok** [comment]
I don’t understand what this PR does!

What is the new CSS for?
Not an horizontal menu, the other ticket mentions that another module is needed for that (which seems good, no need to do everything in this module)
But also probably not moving the admin-interface theme CSS into a separate file, as the HTML template was not changed.  So I’m confused :slightly_smiling_face:

**Comment by fabiocaccamo** [comment]
@merwok this PR improve style for the integration with `django-admin-index` package, as already does for `django-modeltranslation` and other packages.

**Pull request merged**
