### PR TITLE
Fix #15 -- Add a theme for the default Django Admin

### LINKED ISSUE #15: More base themes
This Django app is amazing, such a great idea. We have several sites running with Django and we are starting using it to avoid confusion between sites and environments (local/test/live...). For my use case, it would make this even easier to deploy if there were a few more themes built in. 

I'm no designer so my first experimentations were a bit disappointing. I ended up with a theme inspired by [Bootstrap's docs](https://getbootstrap.com/) site, and I'd happily contribute back here. Would you be open to receive more themes? I was thinking of adding a fixtures that one would optionally load using:
```
python manage.py loaddata super_duper_theme.json
```
Then add a screenshot somewhere to document the theme's existence in the README? Do you have more docs somewhere?

### PR DESCRIPTION
**Pull request by browniebroke**
- Add through a fixture
- Adding a basic doc on how to add more

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
After having see how Slack manages themes I had some ideas, I think that I will add a field where to copy/paste the theme settings. 
Using the fixtures is "too much" for developers and the admin customization should be designer-friendly.

Thanks anyway for the PR.

**Comment by browniebroke** [comment]
No worries, glad I could contribute to the idea.

**Comment by fabiocaccamo** [comment]
@browniebroke I created 2 new themes, Bootstrap and Foundation.
I can provide these themes automatically using migrations, alternatively I can just create a fixture and explain in the documentation how to install the new themes via fixtures.
Have you any suggestion?

**Comment by browniebroke** [comment]
I didn't go for the migration idea, as I consider theme as an optional thing, and usually, a migration is more in "apply everywhere" spirit. 
I guess when installing this app for the first time, I wouldn't mind having multiple themes loaded by default on my local machine, but when deploying it's great to be able to say "just load that one" via the config, without having to do anything manually after deploying.
Maybe there is something possible with settings to let the users control which themes to install?

**Comment by fabiocaccamo** [comment]
You're right, thanks.

**Pull request closed without merging**
