### PR TITLE
Add sticky action button option.

### PR DESCRIPTION
**Pull request by theSinner**
Hi

In many cases, I faced with this problem that I filled all the required fields, but need to scroll down too much to be able to save the form, especially in a form with large components like a map.
So I decided to add a sticky action button to give the form’s action button a fixed position (like the screenshot).
I know this is not everyone's problem, but I thought maybe it's useful for others, too.

Screen Shot 2021-01-24 at 19 36 54

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
@theSinner thank you for this PR, it sounds interesting. I will test it as soon as possible.
The `save_on_top` `ModelAdmin` option doesn't solved your problem?

**Comment by theSinner** [comment]
@fabiocaccamo 
Thank you. Yes I tested it before and it’s useful, but it only works in some cases. Because it will go off the screen after scrolling, too.

**Comment by fabiocaccamo** [comment]
@theSinner does it work for changelist too (when there is soma `list_editable`) ?

**Comment by theSinner** [comment]
> @theSinner does it work also for changelist (when there is some `list_editable`) ?

I want to, but I didn't find any different class name or ID in the pages with or without the ` list_editable` option. In both of them, the main tag's ID is `changelist-form` and the bottom part has a `paginator` class. The only difference is an input tag in the paginator part and the only solution I know is the :has() [selector](https://caniuse.com/css-has) which has a none browser support.😅

**Comment by fabiocaccamo** [comment]
@theSinner I think that there could be another option like `sticky_paginator`.

**Comment by theSinner** [comment]
> @theSinner I think that there could be another option like `sticky_pagination`.
> So a new options group in the theme admin containing both `sticky_action_buttons` and `sticky_pagination`.

Yes, it's a good idea. Can you suggest a name for the admin group of these values? I’m not sure but I was thinking about a “Sticky” group and keep all sticky options together like:

**Sticky**
- List filter
- List pagination
- Form action button

**Comment by fabiocaccamo** [comment]
@theSinner for scalability and consistency I grouped the theme options by context and not by functionality, I would continue to maintain this logic given that in the future there may be new options for already existing contexts. 

**Model fields:**
I would name the fields `form_pagination_sticky` and `form_submit_sticky`. 
I think it is better don't use the word "action" to avoid confusion with [admin actions](https://docs.djangoproject.com/en/3.1/ref/contrib/admin/actions/).

In the model detail page, if `save_on_top=True`, the `form_submit_sticky` option should affect both rows correctly or doesn't affect at all the submit row on top. 

**Model admin fieldsets:**
I would name the fieldset `Form Controls` and position it before `List Filter`.


Please test the options in **Changelist**, **Add**, **Change**,  model admin pages.

**Comment by theSinner** [comment]
@fabiocaccamo 
Sorry, I have been very busy lately and I couldn't respond sooner. I fixed the field's names and also the admin structure.
I thought having two sticky `submit-row` only makes the space smaller. So I set sticky styles only to the bottom one.

**Comment by fabiocaccamo** [comment]
@theSinner don't worry, there is no rush. I agree with your decision to make sticky only the `submit-row` on bottom. Thank you again.

**Comment by merwok** [comment]
Sticky pagination means fixed position for the bar with information at the bottom of a list page?

**Comment by fabiocaccamo** [comment]
- Sticky pagination means the paginator row in the changelist view, if `list_editable` is not empty the it will include also the save button.
- Sticky form controls means the submit row containing the save/delete buttons in the model change page.

**Pull request merged**
