### PR TITLE
Run tests using postgresql

### PR DESCRIPTION
**Pull request by browniebroke**
As it's raising an exception on my machine:
```
IntegrityError: duplicate key value violates unique constraint "admin_interface_theme_pkey"
DETAIL:  Key (id)=(1) already exists.
```
- [x] Reproduce issue
- [x] Fix it

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
I think the exception is raised [here](https://github.com/fabiocaccamo/django-admin-interface/blob/master/admin_interface/models.py#L37) and this could be the solution: https://docs.djangoproject.com/en/1.11/ref/models/options/#select-on-save

**Comment by browniebroke** [comment]
Yes, I agree with the source line you pointed at. 
The exception would show up when creating the first non-default Theme on a clean installation, for instance when installing an optional theme.
I'll try your solution shortly.

**Comment by fabiocaccamo** [comment]
Does the exception show up when you create a Theme using `loaddata` with a fixture or using the admin?

**Comment by browniebroke** [comment]
Using loaddata definitely, but I'm 60% sure it also occurred using the admin. I'll see if I can try out.

**Comment by fabiocaccamo** [comment]
How did you found the problem?
With this PR tests are now executed using only postgresql, I think that they should be executed using multiple databases, didn't you agree?

**Comment by browniebroke** [comment]
I tested various things and nailed it down after a few tries.

We could add other databases, but I'm not convinced it would be worth the effort. I personally care mostly about Postgresql, as it's currently my go-to database for anything a bit serious.

**Comment by fabiocaccamo** [comment]
@browniebroke I added postgres to tox/travis CI.

**Pull request closed without merging**
