### PR TITLE
Fix django default appconfig deprecation warning

### LINKED ISSUE #140: Deprecation notice for default_app_config
**Python version**
n/a

**Django version**
3.2.9

**Package version**
0.18.2

**Current behavior (bug description)**
Run an app or tests with warnings enabled, see:
```
$venv/lib/python3.9/site-packages/django/apps/registry.py:91: RemovedInDjango41Warning: 'admin_interface' defines default_app_config = 'admin_interface.apps.AdminInterfaceConfig'. Django now detects this configuration automatically. You can remove default_app_config.
    app_config = AppConfig.create(entry)
```

**Expected behavior**
No warning

### PR DESCRIPTION
**Pull request by merwok**
fixes #140

### CODE REVIEW

**Comment by merwok** [comment]
Forgot that keeping forks in sync with github is not convenient — pulled and merged upstream.

I’ll rebase or you’ll squash merge!

**Review by fabiocaccamo — CHANGES_REQUESTED** [review]
Is it safe to remove this also for older django versions?

I would keep it if django.version < 4 to be 101% backward compatible.

**Comment by merwok** [comment]
I’m not fully sure, would need a test project with these versions.  The difference is that they would have to have `'admin_interface.apps.AdminInterfaceConfig'` in INSTALLED_APPS instead of `'admin_interface'` alone.

---

On the topic of supported versions, I also wanted to ask you how you would feel about reducing them!
Keeping 4 older python versions and 4 django versions (LTS or current):

```diff
diff --git a/tox.ini b/tox.ini
--- a/tox.ini
+++ b/tox.ini
@@ -1,35 +1,28 @@
 [tox]
 envlist =
-    py27-{dj17,dj18,dj19,dj110,dj111}-{sqlite,postgres},
-    py35-{dj18,dj19,dj110,dj111,dj20,dj21,dj22}-{sqlite,postgres},
-    py36-{dj18,dj19,dj110,dj111,dj20,dj21,dj22,dj30,dj31,dj32,djmaster}-{sqlite,postgres},
-    py37-{dj20,dj21,dj22,dj30,dj31,dj32,djmaster}-{sqlite,postgres},
-    py38-{dj22,dj30,dj31,dj32,djmaster}-{sqlite,postgres},
-    py39-{dj22,dj30,dj31,dj32,djmaster}-{sqlite,postgres},
+    py27-dj111-{sqlite,postgres},
+    py36-{dj22,dj31,dj32,djmaster}-{sqlite,postgres},
+    py37-{dj22,dj31,dj32,djmaster}-{sqlite,postgres},
+    py38-{dj22,dj31,dj32,djmaster}-{sqlite,postgres},
+    py39-{dj22,dj31,dj32,djmaster}-{sqlite,postgres},
+    py310-{dj22,dj31,dj32,djmaster}-{sqlite,postgres},
```

**Comment by fabiocaccamo** [comment]
I use this library on some very old projects and I like to update it to the latest version to use new features.

**Review by fabiocaccamo — APPROVED** [review]

**Pull request merged**
