### PR TITLE
Basic horizontal menu implementation

### PR DESCRIPTION
**Pull request by lorenzomorandini**
I think this should work as a basic implementation of a horizontal menù. I'm not sure how you want to organize your css or if you want to add new model fields to customize the menù (maybe toggle it's visibility too). I tried to touch existing code as little as possible.

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
Thank you! I will merge and integrate it in the next days. 🎉

**Comment by lorenzomorandini** [comment]
Great, pay attention it is not responsive.
Also credits to @Robert-Lebedeu for the template tag

**Comment by fabiocaccamo** [comment]
I quickly tested this PR, it is pretty far from being merged, some work should be done before publish it, but it is a good starting point. Thank you.

**Comment by fabiocaccamo** [comment]
PR #87 improved compatibility with `django-admin-index`.
If you need to use horizontal menus you can install [django-admin-index](https://github.com/maykinmedia/django-admin-index).

**Pull request closed without merging**
